### ISSUE TITLE
Commit

### ISSUE THREAD

**Issue by aggelosQQ** [ImmaFreedom-Dev/CustomImmaFreedomMod#6]
Last commit 26 days ago :P

**Comment by LegendIsAwesomes** [comment]
All mine are on netbeans, can't commit it till my broken/fractured wrist has healed.

**Comment by aggelosQQ** [comment]
Alright

**Comment by DUFCLiam** [comment]
I am no longer developer xD

**Comment by LegendIsAwesomes** [comment]
@DUFCLiam make PRs and earn it back then.

**Comment by DUFCLiam** [comment]
I know, I would like suggestions on what to make.

**Comment by LegendIsAwesomes** [comment]
Just make anything for a freedom mod ATM

**Comment by DUFCLiam** [comment]
I am currently doing a Patch :P

**Comment by DUFCLiam** [comment]
Requesting closure of this issue as there should be a new issue merged. @LegendIsAwesomes
